spring.application.name=Additionbefe
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/Addition
spring.datasource.username=root
spring.datasource.password=Rahul@666
spring.jpa.hibernate.ddl-auto=update